version: "3"
services:
  contactservices:
    build:
      context: .
      dockerfile: ./contact_service/Dockerfile
    restart: on-failure
    container_name: contactimage
    ports:
      - 8082:8082
    networks:
      - app-net
      
  userservices:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: on-failure
    container_name: userimage
    ports:
      - 8081:8081
    depends_on:
      - contactservices
    networks:
      - app-net
    environment:
      - WAIT_HOSTS=contactservices:8082


networks:
  app-net:
