version: "3"
services:
  userservices:
    image: anil76201/userimage
    ports:
      - 8081:8081
    depends_on:
      - contactservices
    networks:
      - app-net

  contactservices:
    image: anil76201/contactimage
    ports:
      - 8082:8082
    networks:
      - app-net

networks:
  app-net: